config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :matches, only: [:index, :show]

  root to: "matches#index"
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/matches_controller.rb
# frozen_string_literal: true

class MatchesController < ApplicationController
  def index
    service           = CrickinfoService.new
    all_matches       = service.get_all_matches_info
    @live_matches     = all_matches['live_matches']
    @previous_matches = all_matches['previous_matches']
  end

  def show
    service = CrickinfoService.new
    @match  = service.get_match_info(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def formatted_match_end_result(end_result)
    return "" if end_result.blank?

    if end_result != "tied"
      "#{end_result} this match"
    else
      "Match got tied"
    end
  end

  def handle_css_class(end_result)
    if end_result.present?
      ""
    else
      "green-color"
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "EspnCricinfoFrontend" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <%= link_to root_path, class: "navbar-brand" do %>
          <b>
            EspnCricinfoFrontend
          </b>
        <% end %>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-9 container-body">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>
      <footer>
        <p>&copy; EspnCricinfo 2016</p>
      </footer>
    </div>
  </body>
</html>

app/views/matches/_match.html.erb
<tr>
  <td>
    <%= link_to match_path(match["id"]) do %>
      <b><%= match["team1"] %></b> v <b><%= match["team2"] %></b>
    <% end %>
  </td>
</tr>

app/views/matches/index.html.erb
<div>
  <div>
    <h3>LIVE SCORES</h3>
    <% if @live_matches.present? %>
      <table>
        <tbody>
          <% @live_matches.each do |match| %>
            <%= render partial: 'match', locals: { match: match } %>
          <% end %>
        </tbody>
      <% else %>
        No live matches found!
      <% end %>
    </table>
  </div>
  <div>
    <h3>PREVIOUS MATCH RESULTS</h3>
    <% if @previous_matches.present? %>
      <table>
        <tbody>
          <% @previous_matches.each do |match| %>
            <%= render partial: 'match', locals: { match: match } %>
          <% end %>
        </tbody>
      </table>
    <% else %>
      No previous matches found!
    <% end %>
  </div>
</div>

app/views/matches/show.html.erb
<div>
  <h2 data-info="match-title" data-match-id="<%= @match["id"] %>">
    <%= @match["title"] %><span>(<%= @match["first_batting_team"] %> chose batting first)</span>
  </h2>

  <div data-info="match-end-result" class="match-end-result">
    <%= formatted_match_end_result(@match["end_result"]) %>
  </div>

  <div data-info="first-batting-team-info" class="first-batting-team">
    <% if @match["first_batting_team_info"] && @match["first_batting_team_info"]["played"] %>
      <%= @match["first_batting_team_info"]["status"] %>
    <% end %>
  </div>

  <div data-info="current-batting-team-info" class="current-batting-team <%= handle_css_class(@match["end_result"]) %>">
    <%= @match["current_batting_team_info"]["status"] %>
  </div>
  <br/ >

  <div class="back-link">
    <%= link_to "Back", root_path %>
  </div>
</div>

<% if @match["end_result"].blank? %>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.0/jquery-ui.min.js"></script>
  <script type="text/javascript">
    var ws = new WebSocket("<%= ENV["CLOUDAMQP_STOMP_URL"] %>");
    var client = Stomp.over(ws);

    // RabbitMQ SockJS does not support heartbeats so disable them.
    client.heartbeat.outgoing = 0;
    client.heartbeat.incoming = 0;

    var onDebug = function(m) {
      console.log("DEBUG", m);
    };

    var onConnect = function() {
      console.log("Connected");
      var matchID                       = $("[data-info~=match-title]").data('match-id');
      var firstBattingTeamScoreInfo     = "";
      var firstBattingTeamInfoElement   = $("[data-info~=first-batting-team-info]");
      var currentBattingTeamInfoElement = $("[data-info~=current-batting-team-info]");
      var matchEndResultElement         = $("[data-info~=match-end-result]");

      client.subscribe("/exchange/match_scores/match-" + matchID, function(data) {
        var match = JSON.parse(data.body);

        if (match["first_batting_team_info"]["played"]) {
          firstBattingTeamInfoElement.html(match["first_batting_team_info"]["status"]);
        }

        currentBattingTeamInfoElement.html(match["current_batting_team_info"]["status"]);
        currentBattingTeamInfoElement.effect("highlight", {}, 1500);

        var matchEndResult = match["end_result"];

        if(matchEndResult) {
          if (matchEndResult == "Tied") {
            matchEndResultElement.html("Match tied");
          }else {
            matchEndResultElement.html(matchEndResult + " this match");
          }
          matchEndResultElement.effect("highlight", {}, 1500);
          currentBattingTeamInfoElement.removeClass('green-color');
        }
      });
    };

    var onError = function(e) {
      console.log("ERROR", e);
    };

    client.debug = onDebug;
    client.connect("<%= ENV["CLOUDAMQP_USER"] %>","<%= ENV["CLOUDAMQP_PASSWORD"] %>",
                   onConnect, onError,"<%= ENV["CLOUDAMQP_VHOST"] %>");
  </script>
 <% end %>